services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgresql
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin

  backend:
    container_name: backend
    depends_on:
      - postgresql
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/.venv

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgresql:
  pgadmin:
