[project]
name = "backend"
version = "0.1.0"
description = "DB app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.6",
    "pydantic-settings>=2.7.1",
    "uvicorn>=0.34.0",
]
